---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx # Fixed indentation
  ports:
    - port: 80
      targetPort: 80 # Moved inside ports
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx # Moved inside labels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: asia-southeast1-docker.pkg.dev/$GOOGLE_PROJECT/kenneth-artifacts/nginx:latest # Fixed indentation
